name = "hive"
compatibility_date = "2026-06-13"
compatibility_flags = ["nodejs_compat"]
main = "./src/server.ts"

[observability]
enabled = true

[vars]
SUPABASE_URL = "https://icbmhwuzmazxwsrcough.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable_Cp0lPDleO8haCvdYLm-0zA_3GHp3pZA"
